backend:
  name: github
  repo: alex-spare-acc/astro-gitops-cms
  branch: main
  base_url: https://decap-oauth.olsvcs.workers.dev # URL вашага воркера з Cloudflare
  auth_endpoint: auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    fields:
      - { label: "Page title", name: "title", widget: "string" }
      - { label: "SEO Description", name: "description", widget: "string" }
      - { label: "Hero Banner", name: "heroText", widget: "text" }
