backend:
  name: github
  repo: alex-spare-acc/astro-gitops-cms # Заполните после Шага 3
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Страницы"
    folder: "src/content/pages"
    create: true
    fields:
      - { label: "Заголовок страницы", name: "title", widget: "string" }
      - { label: "Описание для SEO", name: "description", widget: "string" }
      - { label: "Главный баннер (Hero)", name: "heroText", widget: "text" }
